---

#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail: msg="{{ item }} is empty or not defined"
  when: vars[item] is undefined or vars[item] == ""
  with_items:
    - kopia__s3_bucket
