---

- name: "Install | Compute install dir"
  set_fact:
    kopia__install_dir: "{{ kopia__bin | dirname }}"

- name: "Install | Ensure install dir exists"
  become: true
  file:
    path: "{{ kopia__install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

# -------- Download & install Kopia CLI --------
- name: "Install | Download Kopia {{ kopia__version }}"
  become: true
  get_url:
    url: "{{ kopia__asset_download_url }}"
    dest: "/tmp/kopia-{{ kopia__version }}-linux-x64.tar.gz"
    mode: "0644"
    force: true

- name: "Install | Unpack Kopia archive"
  become: true
  unarchive:
    src: "/tmp/kopia-{{ kopia__version }}-linux-x64.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/kopia-{{ kopia__version }}-linux-x64/kopia"

- name: "Install | Install Kopia binary"
  become: true
  copy:
    src: "/tmp/kopia-{{ kopia__version }}-linux-x64/kopia"
    dest: "{{ kopia__bin }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: "Show installed Kopia path"
  debug:
    msg: "Kopia installed at {{ kopia__bin }}"

# -------- Layout config dirs expected by the role --------
- name: "Install | Ensure Kopia config directories exist"
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/kopia
    - "{{ kopia__paths_dir }}"
    - /etc/kopia/meta.d
    - "{{ kopia__lock_file | dirname }}"

- name: "Install | Seed env file (only if missing)"
  become: true
  copy:
    dest: "{{ kopia__env_file }}"
    owner: root
    group: root
    mode: "0600"
    force: false
    content: |
      # Kopia S3 credentials & repo settings (managed by Ansible/Vault)
      AWS_ACCESS_KEY_ID=
      AWS_SECRET_ACCESS_KEY=
      AWS_REGION={{ kopia__s3_region }}
      # Optional: AWS_SESSION_TOKEN=
      # Repo settings used by 'repository connect'
      KOPIA_S3_BUCKET={{ kopia__s3_bucket }}
      KOPIA_S3_PREFIX={{ kopia__repo_prefix }}

# Optional sanity check (won't fail the run if repo not connected yet)
- name: "Install | Check Kopia version"
  become: true
  command: "{{ kopia__bin }} --version"
  register: kopia_version_out
  changed_when: false
  failed_when: false

- name: "Kopia version output"
  debug:
    var: kopia_version_out.stdout
