---
default_install_hook_types:
  - pre-commit
  - commit-msg

exclude: "(postCommand.sh|docker/legacy/|vault|dist|plugins|creds|jinja|jinja2|j2|groovy|sql|csv|sln|devcontainer-lock.json|devcontainer.json)"

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # Yaml linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1524"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: forbid-submodules

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=240]

  # https://github.com/compilerla/conventional-pre-commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
      - id: check-vault-encryption
        name: Check that Ansible vault files are encrypted
        entry: ./scripts/check-encryption.sh
        language: system
        types: [file]
        stages: [pre-commit]
