---
# Ansible yaml invengtory file for development environment
all:
  children:
    flatcar:
      hosts:
        edge01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22
        worker01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22

    github_runner:
      hosts:
        edge01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22

    services:
      hosts:
        hello-world@edge01:
        ingress@edge01:
        whoami@edge01:
        github-runner@edge01:

    runners:
      hosts:
        edge01:
