---
# Ansible yaml invengtory file for development environment
all:
  children:
    flatcar:
      hosts:
        edge01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22
        worker01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22

    github_runner:
      hosts:
        edge01:
          ansible_host: 3.124.205.98
          ansible_user: core
          ansible_port: 22

    services-edge01:
      hosts:
        hello-world-01@edge01:
        hello-world-02@edge01:
        ingress-01@edge01:
        whoami-01@edge01:

    runners:
      hosts:
        edge01:
