---
- name: "Image | Pull docker_systemd image {{ docker_systemd_service__image }}"
  become: true
  changed_when: false
  community.docker.docker_image:
    name: "{{ docker_systemd_service__image }}"
    source: pull
  when:
    - (docker_systemd_service__image_pull_policy == "always")
    - not docker_systemd_service__restart == 'yes'

- name: "Image | Pull docker_systemd image {{ docker_systemd_service__image }}"
  become: true
  changed_when: false
  community.docker.docker_image:
    name: "{{ docker_systemd_service__image }}"
    source: pull
  when:
    - (docker_systemd_service__image_pull_policy == "ifnotpresent")
    - not docker_systemd_service__restart == 'yes'
