---
- import_tasks: check_vars.yml
  tags:
    - docker_systemd_service
    - docker_systemd_service:check_vars
    - check_vars

- import_tasks: image.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:image
    - image

- import_tasks: validate_params.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:validate_params
    - validate_params

- import_tasks: compile_params.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:compile_params
    - compile_params

- import_tasks: install.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:install
    - install

- import_tasks: uninstall.yml
  when: docker_systemd_service__state == "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:uninstall
    - uninstall

- include_role:
    name: systemd_timer
  vars:
    systemd_timer__name: "{{ docker_systemd_service__name }}_restart_timer"
    systemd_timer__enabled: "{{ docker_systemd_service__enabled }}"
    systemd_timer__masked: "{{ docker_systemd_service__masked }}"
    systemd_timer__state: "{{ docker_systemd_service__state }}"
    systemd_timer__oncalendar: "{{ docker_systemd_service__restart_timer_oncalendar }}"
    systemd_timer__command: "{{ docker_systemd_service__restart_timer_command }}"
  when:
    - docker_systemd_service__restart_timer|bool
    - not docker_systemd_service__restart == 'yes'
  tags:
    - docker_systemd_service
    - docker_systemd_service:uninstall
    - uninstall

- meta: flush_handlers
