FROM traefik/whoami:latest
LABEL maintainer="Karsten Jakobsen <karsten@karstenjakobsen.dk>"

# Add any additional configuration or files if needed
# For example, you can copy custom configuration files or scripts
# COPY my-custom-config.toml /etc/traefik/traefik.toml
