---
target_host: edge01
service_name: hello-world-01
image: "docker.io/karstenjakobsen/shiplite-hello-world:devel-8629a8c"
env:
  TZ: "Europe/Copenhagen"
  SECRET: "{{ secrets.secret__hello_world_01 }}"
ports:
  - "8085:8080"
