---
target_host: edge01
service__replicas:
  - service__name: hello-world
    service__image: "docker.io/karstenjakobsen/shiplite-hello-world:devel-8629a8c"
    service__env:
      TZ: "Europe/Copenhagen"
      SECRET: "{{ secrets.secret__hello_world }}"
      PEST: "Ko"
      TEST: "Test"
    service__labels:
      traefik.enable: true
      traefik.http.routers.hello-world.rule: Host(`hello-world.karstenjakobsen.dk`)
      traefik.http.routers.hello-world.entrypoints: https
      traefik.http.routers.hello-world.tls: true
      traefik.http.routers.hello-world.tls.certresolver: letsencrypt
      traefik.http.routers.hello-world.service: hello-world
