---
target_host: edge01
service__replicas:
  - service__name: hello-world-01
    service__image: "docker.io/karstenjakobsen/shiplite-hello-world:devel-8629a8c"
    service__env:
      TZ: "Europe/Copenhagen"
      SECRET: "{{ secrets.secret__hello_world }}"
    service__labels:
      traefik.enable: true
      traefik.http.routers.hello-world.rule: Host(`hello-world.karstenjakobsen.dk`)
      traefik.http.routers.hello-world.entrypoints: http
      traefik.http.routers.hello-world.service: hello-world-01
