# defaults/main.yml  — kopia__backup role

# ===== Repo / S3 backend (per-host repo in a shared bucket) =====
kopia__s3_bucket: "futurebanana-backups-prod"
kopia__s3_region: "eu-central-1"
# Prefix for this host's repository; override per host if needed
kopia__repo_prefix: "kopia/{{ inventory_hostname }}"
# Optional: different creds per host via env file templated by the role
kopia__env_file: "/etc/kopia/config.env"

# ===== Binary / paths =====
kopia__bin: "/opt/bin/kopia"            # preferred location (Flatcar, etc.)
kopia__paths_dir: "/etc/kopia/paths.d"     # where per-service *.list/*.kopiaignore live
kopia__lock_file: "/var/lock/kopia.lock"
kopia__version: "0.21.1"                # override to upgrade
kopia__asset_download_url: "https://github.com/kopia/kopia/releases/download/v{{ kopia__version }}/kopia-{{ kopia__version }}-linux-x64.tar.gz"

# ===== Execution model =====
kopia__use_central_timer: true             # one aggregate snapshot job per host
kopia__timer_calendar: "*-*-* 02:00:00"    # systemd OnCalendar for the aggregate job
kopia__run_maintenance_post_backup: true   # explicit quick maintenance after backup
kopia__enable_snapshot_expire: false       # usually not needed; policies handle retention

# ===== Global policy defaults (can be overridden per path/service) =====
kopia__policy_global:
  compression: "zstd"
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_annual: 0

# ===== Default ignore patterns (merged with per-service excludes) =====
kopia__default_excludes:
  - "**/*.log"
  - "**/cache/**"
  - "**/tmp/**"
  - "**/.cache/**"
  - "**/lost+found/**"

# ===== Optional: tags applied to all snapshots (merged with per-service tags) =====
kopia__default_tags:
  host: "{{ inventory_hostname }}"
  env: "{{ dev | default('dev') }}"

# ===== Optional: Kopia server (Web UI) =====
kopia__server_enabled: false
kopia__server_address: "127.0.0.1:51515"
kopia__server_username: "admin"
kopia__server_password: ""  # set via vault/host_vars; if empty, role generates a random one

# ===== Aggregate job inputs =====
# The role will scan group_vars/host_vars service definitions and build files under kopia__paths_dir.
# You can also feed extra arbitrary paths here (outside of service objects).
kopia__extra_paths: []      # e.g. ["/etc", "/opt/configs"]
kopia__extra_excludes: []   # e.g. ["**/node_modules/**"]

# ===== Per-service backup schema (example defaults; overridden in your service vars) =====
# The role will look for `service__replicas[].service__backup` on the host
# and materialize:
#  - /etc/kopia/paths.d/<service>.list
#  - /etc/kopia/paths.d/<service>.kopiaignore
#  - optional per-path policy via `kopia policy set <path> ...`

# ===== Maintenance ownership (only one client should own full/quick maintenance) =====
kopia__maintenance_owner: true
kopia__quick_interval: "1h"     # used if you manage intervals via 'kopia maintenance set'
kopia__full_interval: "24h"

# ===== Safety / resource controls for systemd unit =====
kopia__service_cpu_quota: "50%"      # e.g., "50%" or empty for no limit
kopia__service_memory_max: "1G"      # e.g., "1G" or empty for no limit
kopia__nice: 10                      # lower priority IO/CPU
