---
- hosts: services
  gather_facts: false
  strategy: free
  serial: 10

  roles:
    - role: docker_systemd_service
      delegate_to: "{{ target_host }}"
      vars:
        docker_systemd_service__name: "{{ service_name }}"
        docker_systemd_service__image: "{{ image }}"
        docker_systemd_service__state: started
        docker_systemd_service__ports: "{{ ports }}"
        docker_systemd_service__env: "{{ env }}"
        docker_systemd_service__volumes: "{{ volumes | default([]) }}"
        docker_systemd_service__labels: "{{ labels | default([]) }}"
