---
- hosts: services
  gather_facts: false
  strategy: free
  serial: 10

  # Include secrets
  pre_tasks:

    - name: Include vars of secrets.yml into the 'secrets' variable.
      ansible.builtin.include_vars:
        file: ../hosts/{{ environment_name }}/static_vars/{{ ansible_host }}_secrets.yml
        name: secrets

    # Fail if secrets is not defined
    - name: Fail if secrets is not defined
      ansible.builtin.fail:
        msg: "The 'secrets' variable is not defined. Please check your secrets.yml file."
      when: secrets is not defined

  roles:
    - role: docker_systemd_service
      delegate_to: "{{ target_host }}"
      vars:
        docker_systemd_service__name: "{{ service_name }}"
        docker_systemd_service__image: "{{ image }}"
        docker_systemd_service__state: started
        docker_systemd_service__ports: "{{ ports }}"
        docker_systemd_service__env: "{{ env }}"
        docker_systemd_service__volumes: "{{ volumes | default([]) }}"
        docker_systemd_service__labels: "{{ labels | default([]) }}"
