---
- hosts: services
  gather_facts: false
  # strategy: free
  serial: 10

  # Include secrets
  pre_tasks:
    - name: "Include vars of secrets 'secrets' variable."
      ansible.builtin.include_vars:
        file: ../hosts/{{ environment_name }}/secrets/{{ ansible_host }}.vault.yml
        name: secrets

    # Fail if secrets is not defined
    - name: Fail if secrets is not defined
      ansible.builtin.fail:
        msg: "The 'secrets' variable is not defined. Please ensure that the secrets file exists and is properly encrypted."
      when: secrets is not defined

    - debug:
        msg:
          - "{{ service__labels | traefik2dns | default([]) }}"
          - "{{ hostvars[target_host].ansible_host }}"
          - "{{ hostvars[target_host].inventory_hostname }}"

  roles:

    - name: Deploy docker services via systemd
      role: docker_systemd_service
      delegate_to: "{{ target_host }}"
      become: true
      vars:
        docker_systemd_service__name: "{{ service__name }}"
        docker_systemd_service__image: "{{ service__image }}"
        docker_systemd_service__state: started
        docker_systemd_service__network_mode: "{{ service__network_mode | default('bridge') }}"
        docker_systemd_service__ports: "{{ service__ports | default([]) }}"
        docker_systemd_service__env: "{{ service__env | default({}) }}"
        docker_systemd_service__volumes: "{{ service__volumes | default([]) }}"
        docker_systemd_service__labels: "{{ service__labels | default({}) }}"
        docker_systemd_service__backup: "{{ service__backup | default(false) }}"
        docker_systemd_service__cmd: "{{  service__cmd | default('') }}"

    # Create A record for hosts in 'ingress' group
    - name: Create DNS records for services
      role: dns_records
      vars:
        dns_records__name:
          - "{{ hostvars[target_host].inventory_hostname }}"
        dns_records__value: "{{ hostvars[target_host].ansible_host }}"
      when:
        - target_host in groups['ingress']

    - name: Create DNS records for services with traefik2dns label
      role: dns_records
      vars:
        dns_records__name: "{{ service__labels | traefik2dns | default([]) }}"
        dns_records__value: "{{ hostvars[target_host].ansible_host }}"
      when:
        - target_host not in groups['ingress']
        - (service__labels | traefik2dns | default([])) | length > 0
