---
name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker/**"
  pull_request:
    branches:
      - main
    paths:
      - "docker/**"

permissions: write-all

jobs:
  # Job to run change detection
  detect-changes:
    runs-on: ubuntu-24.04

    # Set job outputs to values from filter step
    outputs:
      whoami: ${{ steps.filter.outputs.whoami }}
      hello-world: ${{ steps.filter.outputs.hello-world }}
      github-runner: ${{ steps.filter.outputs.github-runner }}
      traefik-ingress: ${{ steps.filter.outputs.traefik-ingress }}

    steps:
      - uses: actions/checkout@v5
        if: ${{ github.event_name != 'pull_request' }}

      # For pull requests it's not necessary to checkout the code
      # Looks for changes in these paths
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            whoami:
              - 'docker/whoami/**'
            hello-world:
              - 'docker/hello-world/**'
            traefik-ingress:
              - 'docker/traefik-ingress/**'
            github-runner:
              - 'docker/github-runner/**'

  whoami:
    needs: detect-changes
    uses: ./.github/workflows/reusable.docker.yaml
    secrets: inherit
    with:
      application_path: docker/whoami
      package_name: karstenjakobsen/evercall-whoami
      release: ${{ github.event_name != 'pull_request' }}
    if: ${{ needs.detect-changes.outputs.whoami == 'true' }}

  hello-world:
    needs: detect-changes
    uses: ./.github/workflows/reusable.docker.yaml
    secrets: inherit
    with:
      application_path: docker/hello-world
      package_name: karstenjakobsen/evercall-hello-world
      release: ${{ github.event_name != 'pull_request' }}
    if: ${{ needs.detect-changes.outputs.hello-world == 'true' }}

  traefik-ingress:
    needs: detect-changes
    uses: ./.github/workflows/reusable.docker.yaml
    secrets: inherit
    with:
      application_path: docker/traefik-ingress
      package_name: karstenjakobsen/evercall-traefik-ingress
      release: ${{ github.event_name != 'pull_request' }}
    if: ${{ needs.detect-changes.outputs.traefik-ingress == 'true' }}

  github-runner:
    needs: detect-changes
    uses: ./.github/workflows/reusable.docker.yaml
    secrets: inherit
    with:
      application_path: docker/github-runner
      package_name: karstenjakobsen/shiplite-github-runner
      release: ${{ github.event_name != 'pull_request' }}
    if: ${{ needs.detect-changes.outputs.github-runner == 'true' }}
