---
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ansible/hosts/dev/host_vars/*@edge01.yml"

permissions: write-all

jobs:
  release:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v5
        if: ${{ github.event_name != 'pull_request' }}

      # Setup python
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      # pip install requirements
      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run:
          ansible-playbook -i hosts/dev/inventory.yml playbooks/services.yml --check
