---
name: Release Services Development

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ansible/hosts/dev/host_vars/**"
  pull_request:
    branches:
      - main
    paths:
      - "ansible/hosts/dev/host_vars/**"

permissions: write-all

jobs:
  # Job to run change detection
  detect-changes:
    runs-on: ubuntu-24.04

    # Set job outputs to values from filter step
    outputs:
      github-runner-01: ${{ steps.filter.outputs.github-runner-01 }}
      hello-world-01: ${{ steps.filter.outputs.hello-world-01 }}
      hello-world-02: ${{ steps.filter.outputs.hello-world-02 }}
      traefik-ingress-01: ${{ steps.filter.outputs.traefik-ingress-01 }}
      whoami-01: ${{ steps.filter.outputs.whoami-01 }}

    steps:
      - uses: actions/checkout@v5
        if: ${{ github.event_name != 'pull_request' }}

      # For pull requests it's not necessary to checkout the code
      # Looks for changes in these paths
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            whoami-01:
              - 'ansible/hosts/dev/host_vars/whoami-01@edge01.yml'
            hello-world-01:
              - 'ansible/hosts/dev/host_vars/hello-world-01@edge01.yml'
            hello-world-02:
              - 'ansible/hosts/dev/host_vars/hello-world-02@edge01.yml'
            traefik-ingress-01:
              - 'ansible/hosts/dev/host_vars/traefik-ingress-01@edge01.yml'
            github-runner-01:
              - 'ansible/hosts/dev/host_vars/github-runner-01@edge01.yml'

  whoami-01:
    needs: detect-changes
    uses: ./.github/workflows/reusable.services..yaml
    secrets: inherit
    if: ${{ needs.detect-changes.outputs.whoami-01 == 'true' }}
    with:
      environment: dev
      runner: self-hosted
      service: whoami-01@edge01
      check_mode: ${{ github.event_name != 'pull_request' }}
